name: Build image

on: 
  push:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch:
          - [x86_64-linux-gnu, x86_64, /usr/local]

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build base image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          platforms: linux/amd64
          tags: ghcr.io/neugates/build:${{ matrix.arch[1] }}-${{ github.ref_name }}
          file: .github/dockerfile/${{ matrix.arch[1] }}_Dockerfile
          context: .
